spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.micrometer.influx: DEBUG
    io.micrometer.core.instrument.push: DEBUG
